image: alpine/latest
packages:
    - rsync
sources:
    - https://git.sr.ht/~boringcactus/pig.observer
secrets:
    - b5cb9b2b-1461-4486-95e1-886451674a89
tasks:
    - upload: |
        upload-to() {
            dest=$1
            shift
            rsync --rsh="ssh -o StrictHostKeyChecking=no" -rlt8hP --del $@ services@boringcactus.com:$dest
        }
        cd pig.observer
        upload-to /var/www/html/pig.observer/ dist/*
